### ISSUE TITLE
Dark Amaranth Forest with Better End issue

### ISSUE THREAD

**Issue by ghost** [DawnTeamMC/Promenade#151]
### What happened?

Hello, I noticed the fixed bug issue (#117) on this and it seems The Dark Amaranth Forests does the same thing with the BetterEnd mod. Only the fungus spawns but not the Black Dylium.

For BetterEnd and Bclib my server uses the latest versions (3.2.4 and 2.3.4 respectfully) and Promenade as well (3.2.0) if that helps any.

### Dawn API version

4.2.1

### Fabric API version

0.82.0+1.19.4

**Comment by Hugman76** [comment]
If the bug appears when BetterEnd is installed, then this is most likely a BetterEnd issue.

**Comment by Fooddude99** [comment]
Probably and I don't think the mod author for Better End will fix it (They have been known for being uncooperative) so I will just fix the biomes that have been generated by hand with world edit and prevent it from generating anymore in the end. My players have been wanting the wood type and have generated a few of the biomes already so that should suffice.

Ty for your response and have a nice day.
