### ISSUE TITLE
Changes in 2.6.2 made the mod incompatible with BCLib

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [DawnTeamMC/Promenade#83]
### What happened?

Updating from 2.6.1 to 2.6.2 made the mod incompatible with [BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib), the game now crashes on startup. Downgrading back to 2.6.1 fixes the issue. I used TerraBlender in my test, but removing it doesn't fix the issue, so it's a direct conflict between Promenade 2.6.2 and BCLib.

### Dawn API version

3.3.0

### Fabric API version

0.53.4

### Relevant log output

```shell
latest.log and crash log: https://gist.github.com/Footage2-Amply-Pounce/e9120c27dfe1f30304f7c92ab23b4751
```

**Comment by Hugman76** [comment]
This library seems to try to load biomes way too early, even before you try to create or enter a world.
The Fabric API biomes only require a regsitry key to be loaded, and not the biomes themselves. I suggest that you report this issue to their [repository](https://github.com/paulevsGitch/BCLib/issues). They need to make their code datapack-friendly

**Comment by Hugman76** [comment]
This issue might be related to #83

**Comment by TheButterbrotMan** [comment]
I can confirm, I don't have bclib and have this issue.

**Comment by Hugman76** [comment]
The incompatibility with BCLib has been fixed. See https://github.com/paulevsGitch/BCLib/issues/145
You will be able to boot up the game with both mods loaded very fine, when the new version of BCLib gets released.
However, there is still an issue with **world creation** (not loading!), that is caused by the Fabric API. We will follow this issue in #84.
